# Generated by Django 3.2.8 on 2021-10-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_auto_20211020_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='communications.discount'),
        ),
    ]
