# Generated by Django 3.2.8 on 2021-10-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_chat_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='communications.conversation'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.discount'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('S', 'SENT')], max_length=20),
        ),
    ]
