# Generated by Django 3.2.8 on 2021-10-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_auto_20211022_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('P', 'NEW'), ('P', 'RESOLVED')], max_length=10),
        ),
    ]
