# Generated by Django 3.2.8 on 2021-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('R', 'RESOLVED')], max_length=10),
        ),
    ]
