# Generated by Django 3.2.8 on 2021-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('S', 'SENT')], default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('R', 'RESOLVED')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sending_date',
            field=models.DateTimeField(),
        ),
    ]
