# Generated by Django 3.2.8 on 2021-10-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_auto_20211025_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SENT', 'SENT')], default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED')], default='P', max_length=10),
        ),
    ]
